"""Add IP-based rate limiting

Revision ID: a82782b078f8
Revises: c8aefdbf0291
Create Date: 2025-11-26 19:59:49.285481+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82782b078f8'
down_revision: Union[str, None] = 'c8aefdbf0291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emails_email'), 'emails', ['email'], unique=True)
    op.create_table('ip_rate_limits',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('last_created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('count_1h', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_rate_limits_ip_address'), 'ip_rate_limits', ['ip_address'], unique=True)
    op.create_table('rate_limits',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('email_id', app.models.UUID(), nullable=False),
    sa.Column('last_created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('count_1h', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_table('timepoints',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('email_id', app.models.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=50), nullable=False),
    sa.Column('input_query', sa.Text(), nullable=False),
    sa.Column('cleaned_query', sa.Text(), nullable=False),
    sa.Column('is_fictional', sa.Boolean(), nullable=False),
    sa.Column('scene_graph_json', sa.JSON(), nullable=True),
    sa.Column('character_data_json', sa.JSON(), nullable=True),
    sa.Column('dialog_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('segmented_image_url', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timepoints_slug'), 'timepoints', ['slug'], unique=True)
    op.create_table('processing_sessions',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'GENERATING_SCENE', 'GENERATING_IMAGE', 'SEGMENTING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=True),
    sa.Column('progress_data_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timepoint_id', app.models.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['timepoint_id'], ['timepoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_sessions_session_id'), 'processing_sessions', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_sessions_session_id'), table_name='processing_sessions')
    op.drop_table('processing_sessions')
    op.drop_index(op.f('ix_timepoints_slug'), table_name='timepoints')
    op.drop_table('timepoints')
    op.drop_table('rate_limits')
    op.drop_index(op.f('ix_ip_rate_limits_ip_address'), table_name='ip_rate_limits')
    op.drop_table('ip_rate_limits')
    op.drop_index(op.f('ix_emails_email'), table_name='emails')
    op.drop_table('emails')
    # ### end Alembic commands ###
